services:
  - type: web
    name: prototype-ui
    runtime: static
    rootDir: Prototype/PrototypeFrontend/PrototypeUi
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html