@TeapotApi_HostAddress = http://localhost:5186

GET {{TeapotApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TeapotApi_HostAddress}}/api/organizations
Content-Type: application/json

{
	"organizationName": "Teapot",
	"organizationDescription": "Example organization",
	"maxUsers": 25,
	"organizerUserName": "admin",
	"organizerEmail": "admin@example.com"
}

###
