using DataAccess.Models;

namespace DataAccess.Repositories;

/// <summary>
/// Data access interface for TaskBlock entity operations.
/// Manages scheduled time blocks for tasks on the calendar.
/// </summary>
/// <remarks>
/// TaskBlocks are created by the scheduling algorithm and represent when tasks are scheduled.
/// Fixed blocks (for meetings or fixed-time tasks) cannot be moved by the scheduler.
/// </remarks>
public interface ITaskBlockRepository
{
    /// <summary>
    /// Gets all scheduled task blocks for a work profile.
    /// </summary>
    /// <param name="workProfileId">The work profile GUID</param>
    /// <param name="cancellationToken">Token to observe for cancellation requests</param>
    /// <returns>List of all task blocks in the work profile's calendar</returns>
    Task<IReadOnlyList<TaskBlock>> GetByWorkProfileAsync(
        Guid workProfileId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes all non-fixed task blocks for a work profile and replaces them with new blocks.
    /// </summary>
    /// <param name="workProfileId">The work profile GUID</param>
    /// <param name="newBlocks">The new task blocks generated by the scheduling algorithm</param>
    /// <param name="cancellationToken">Token to observe for cancellation requests</param>
    /// <remarks>
    /// Fixed blocks (IsFixed=true) are preserved and not deleted.
    /// Used by the scheduling algorithm to update the task calendar after re-scheduling.
    /// </remarks>
    Task ReplaceAsync(
        Guid workProfileId,
        IReadOnlyList<TaskBlock> newBlocks,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes all scheduled blocks for a specific task.
    /// </summary>
    /// <param name="taskId">The task GUID</param>
    /// <param name="cancellationToken">Token to observe for cancellation requests</param>
    /// <remarks>Used when a task is deleted or when re-scheduling a single task</remarks>
    Task DeleteForTaskAsync(Guid taskId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates or updates a single fixed block for a task.
    /// </summary>
    /// <param name="taskId">The task GUID</param>
    /// <param name="start">The block start date and time</param>
    /// <param name="end">The block end date and time</param>
    /// <param name="cancellationToken">Token to observe for cancellation requests</param>
    /// <remarks>
    /// Deletes any existing blocks for the task first, then inserts a single fixed block.
    /// Used for tasks with IsFixed=true (e.g., meetings at a specific time).
    /// </remarks>
    Task UpsertFixedBlockAsync(Guid taskId, DateTime start, DateTime end, CancellationToken cancellationToken = default);
}
