namespace DataAccess.Models;

/// <summary>
/// Represents a scheduled time block for a task on the user's calendar.
/// Created by the scheduling algorithm to allocate task work time within available working hours.
/// </summary>
/// <remarks>
/// TaskBlocks are generated by the planning/scheduling algorithm based on:
/// - Task duration (TimeEstimate from UserTask)
/// - Available work time (WorkBlocks and WorkBreaks)
/// - Task dependencies and critical path
/// - User's daily workload limits
/// 
/// Each TaskBlock has a start and end date, and may be fixed (immovable) or flexible.
/// Fixed blocks (e.g., for meetings) cannot be moved by the scheduler.
/// </remarks>
public class TaskBlock
{
    /// <summary>Unique identifier for this scheduled task block</summary>
    public Guid Id { get; set; }
    
    /// <summary>Foreign key: the task this block allocates time for</summary>
    public Guid TaskId { get; set; }

    /// <summary>Date and time when this task block starts</summary>
    public DateTime StartDate { get; set; }

    /// <summary>Date and time when this task block ends</summary>
    /// <remarks>Should equal StartDate + task.TimeEstimate for standard scheduling</remarks>
    public DateTime EndDate { get; set; }

    /// <summary>Whether this task block is fixed in the schedule (immovable)</summary>
    /// <remarks>Fixed blocks (e.g., meetings) cannot be rescheduled by the algorithm</remarks>
    public bool IsFixed { get; set; }

    /// <summary>Navigation property: the task this block allocates time for</summary>
    public virtual UserTask Task { get; set; } = null!;
}