// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostApiOrganizationData, PostApiOrganizationErrors, PostApiOrganizationResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiOrganization = <ThrowOnError extends boolean = false>(options?: Options<PostApiOrganizationData, ThrowOnError>) => (options?.client ?? client).post<PostApiOrganizationResponses, PostApiOrganizationErrors, ThrowOnError>({
    url: '/api/Organization',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
