// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://software-engineering-projekt-production.up.railway.app' | (string & {});
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type CreateOrganizationResult = {
    organizationId?: string;
    organizerUserId?: string;
};

export type CreateOrganizationRequest = {
    organizationName?: string | null;
    organizationDescription?: string | null;
    maxUsers?: number;
    organizerUserName?: string | null;
    organizerEmail?: string | null;
};

export type PostApiOrganizationData = {
    body?: CreateOrganizationRequest;
    path?: never;
    query?: never;
    url: '/api/Organization';
};

export type PostApiOrganizationErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostApiOrganizationError = PostApiOrganizationErrors[keyof PostApiOrganizationErrors];

export type PostApiOrganizationResponses = {
    /**
     * Created
     */
    201: CreateOrganizationResult;
};

export type PostApiOrganizationResponse = PostApiOrganizationResponses[keyof PostApiOrganizationResponses];
